services:
  # karlitis:
  #   container_name: karlitis
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://user:password@postgres:5432/db
  #     NODE_ENV: development
  #     PORT: 4000
  #   ports:
  #     - "4000:4000"
  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db